sudo: required

services:
- docker

before_install:
- ls -d mysql_data/* | grep -v .gitignore | xargs rm -rf
- sleep 10
- docker-compose up

script:
- sleep 10
- docker container ls

matrix:
  fast_finish: true
