sudo: required

language: php

php:
- 7.2

services:
- docker

before_install:
- ls -d data/* | grep -v .gitignore | xargs rm -rf
- docker build --tag lamp-base:travis .
- sleep 10
- docker run -d --name lamp -v `pwd`/html:/var/www/html -v `pwd`/data:/var/lib/mysql -p 18367:80 lamp-base:travis

script:
- sleep 10
- docker container ls
- sleep 10
- curl -s -XGET http://localhost:18367
- docker exec -it lamp mysql -e "SELECT 1;"

matrix:
  fast_finish: true
